package main;

public enum EntityType{
    PLAYER, COIN, ENEMY, LEFTWALL, RIGHTWALL, TOPWALL,
        BOTTOMWALL, POWERUP, FREEZEPOWER, BULLET1, BULLET2, BULLET3, FROZENCIRCLE, BOSS1, BOSS2,BOSS3, BOSS1BULLET,BOSS2BULLET, BOSS3BULLET,
    PLAYERWEAPON1, PLAYERWEAPON2, PLAYERWEAPON3, AURA, EXTRALIFE
    }

